// `.env.ts` is generated by the `npm run env` command
//import env from './.env';

export const environment = {
  production: false,
  version: 1,
  serverUrl: 'http://localhost:8000/api/',
  LiveUrl: 'http://34.225.133.232:8000/api/',
  ExcelPath: "http://34.225.133.232/sample/",
  ReportPath : "http://34.225.133.232/report/",
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR']
};
